8may/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Pronia.Core.Models;

namespace _8may.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        [Area("Admin")]

        public IActionResult Index()
        {
            return View();
        }
    }
}

8may/Areas/Admin/Controllers/FeatureController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Pronia.Business.Services.Abstracts;
using Pronia.Core.Models;

namespace _8may.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FeatureController : Controller
    {
       
        private readonly IFeatureService _featureService;
        public FeatureController(IFeatureService featureService)
        {
           _featureService = featureService;
        }
        public IActionResult Index()
        {
            var features = _featureService.GetAll();
            return View(features);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Feature feature)
        {
            _featureService.AddF(feature);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var dfeature = _featureService.Get(x => x.Id== id);
            if(dfeature == null) { throw new NullReferenceException("Null ola bilmez(id)"); }
            return View(dfeature);
        }
        [HttpPost]
        public IActionResult DeletePost(int id)
        {
            _featureService.DeleteF(id);
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id2)
        {
            var ufeature = _featureService.Get(x => x.Id == id2);
            if (ufeature == null) { throw new NullReferenceException("Null ola bilmez"); }
            return View(ufeature);
        }
        [HttpPost]
        public IActionResult UpdatePost(Feature feature)
        {
            _featureService.UpdateF(feature.Id, feature);
            return RedirectToAction("Index");
        }

    }
}

8may/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pronia.Business.Services.Abstracts;
using System.Diagnostics;

namespace _8may.Controllers
{
    //[Area("Admin")]
    public class HomeController : Controller
    {
        IFeatureService _featureService;
        public HomeController(IFeatureService featureService)
        {
            _featureService = featureService;
        }
        public IActionResult Index()
        {
            var features = _featureService.GetAll();
            return View(features);
        }

    }
}

8may/Areas/Admin/Views/Feature/Create.cshtml
<div class="container">
	<div class="row">
        <form action="Create" method="post" >
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Icon</label>
                <input name="Icon" type="text" class="form-control" id="exampleInputEmail1" >
               
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Title</label>
                <input name="Title" type="text" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Description</label>
                <textarea name="Description" row="5" class="form-control"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
	</div>
</div>

8may/Areas/Admin/Views/Feature/Delete.cshtml
@model Feature
<div class="container">
    <div class="row">
<div class="card" style="width: 18rem;">
            <form asp-action="DeletePost" asp-controller="Feature" method="post">

                <div class="card-body">
                    <h5 class="card-title">@Model.Icon</h5> 
                    <h6 class="card-subtitle mb-2 text-muted">@Model.Title</h6>
                    <p class="card-text">@Model.Description</p>
                    <input asp-for="@Model.Id" hidden value="@Model.Id" />
                    <a asp-action="Index" asp-controller="Feature" class="card-link">Go Back</a>
                    
                    <button type="submit" class="btn-outline-danger">Delete</button>
                </div>
   </form>
</div>
</div>
</div>

8may/Areas/Admin/Views/Feature/Index.cshtml
@model List<Feature>
<div class="container">
	<div class="row">
        <div class="col-3 mb-3">
            <a asp-action="Create"class="btn btn-outline-primary">Create Feature</a>
        </div>
		<div class="col-12">

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Id</th>
                        <th scope="col">Icon</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model)
                    {
                        <tr>
                            <th scope="row">1</th>
                            <td>@item.Id</td>
                            <td>@item.Icon</td>
                            <td>@item.Title</td>
                            <td>@item.Description</td>
                            <td><a asp-action="Delete" asp-asp-controller="Feature"  asp-route-id="@item.Id"  class="btn btn-outline-danger">Delete</a></td>
                            <td><a asp-action="Update" asp-asp-controller="Feature" asp-route-id2="@item.Id" class="btn btn-outline-info">Update</a></td>
                        </tr>

                    }
                </tbody>
            </table>

        </div>
	</div>
</div>

8may/Areas/Admin/Views/Feature/Update.cshtml
@model Feature
<div class="container">
    <div class="row">
        <form action="UpdatePost" method="post">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Icon</label>
                <input name="Icon" type="text" class="form-control" id="exampleInputEmail1">

            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Title</label>
                <input name="Title" type="text" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Description</label>
                <textarea name="Description" row="5" class="form-control"></textarea>
            </div>
            <input asp-for="@Model.Id" hidden value="@Model.Id" />
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>